### PR TITLE
Permit single or double dash for command-line options

### PR DESCRIPTION
**Pull request by Lestropie**
@chrisfilo: As requested in in #11.

### CODE REVIEW

**Comment by chrisfilo** [comment]
```
Traceback (most recent call last):

  File "/run.py", line 689, in <module>

    runSubject(app.args.bids_dir, subject_label, os.path.abspath(app.args.output_dir))

  File "/run.py", line 54, in runSubject

    if not app.args.parc:

AttributeError: 'Namespace' object has no attribute 'parc'
```

**Comment by Lestropie** [comment]
Whoops; that should fix it.

Another alternative solution I'm thinking about is to detect whether or not the script is being run within the container (based on the presence of `/version`), and set up the command-line options accordingly. That way, within the container the syntax will be consistent for OpenNeuro / BIDS Apps in general, whereas if run as standalone it will be consistent with the rest of *MRtrix3*.

**Comment by chrisfilo** [comment]
This looks good to me. Do you want to merge this and create a new release so we could deploy it on OpenNeuro?

**Comment by Lestropie** [comment]
I wanted to have more of a play with branching the command-line options depending on whether the script is used in a container or in stand-alone mode. I think eventually it'll be a cleaner solution, but it requires a tweak to *MRtrix3*, which means changing the git commit checkout. So I might stick with this solution for now, and make the modification I have in mind as part of #13.

**Comment by chrisfilo** [comment]
Sounds good to me!

**Pull request merged**
