### PR TITLE
Tag 0.2.1

### PR DESCRIPTION
**Pull request by Lestropie**
Primarily addressing critical error reported in #15, which is currently preventing successful execution of participant level analysis with FreeSurfer parcellation schemes.

### CODE REVIEW

**Comment by Lestropie** [comment]
@chrisfilo: What's the procedure for getting updates pulled to OpenNeuro?

**Comment by chrisfilo** [comment]
Make a release on GitHub ( or push a tag), wait until CircleCi pushes a new image to Docker Hub and then email or message me to update the app on OpenNeuro.

**Comment by Lestropie** [comment]
@chrisfilo @ddshin: Version 0.2.1 is now up on Docker Hub.

**Comment by chrisfilo** [comment]
Deployed!

**Comment by ddshin** [comment]
@Lestropie - Thanks... but I am getting an error at the very beginning. Please see below:

screen shot 2017-09-18 at 12 10 08 am

**Comment by Lestropie** [comment]
ARGH... That'll teach me to test the script using test data! CircleCI's test limitations are a real bummer. I'll need to run through the full pipeline on full data to make sure that's the only remaining glitch (it's the result of needing to tow along various *MRtrix3* updates as I make changes / fixes to this script)... gimme a couple of days...

**Comment by ddshin** [comment]
No problem. Happy to iterate as many times as necessary... so long as we converge to a solution.

**Comment by ddshin** [comment]
Hi Robert,

Checking in to find out when we can get a newer release for testing. Thanks.

David

On Sep 18, 2017 12:56 AM, "Robert Smith" <notifications@github.com> wrote:

ARGH... That'll teach me to test the script using test data! CircleCI's
test limitations are a real bummer. I'll need to run through the full
pipeline on full data to make sure that's the only remaining glitch (it's
the result of needing to tow along various *MRtrix3* updates as I make
changes / fixes to this script)... gimme a couple of days...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/BIDS-Apps/MRtrix3_connectome/pull/18#issuecomment-330150939>,
or mute the thread

**Comment by Lestropie** [comment]
@ddshin: The necessary changes have been made over at #20, and it runs though the test data OK; but I want to run through the script with non-preprocessed data and a FreeSurfer parcellation to make sure that there aren't any remaining gotchas. Because I've had to make changes to *MRtrix3* to support that script, and these changes then get merged with other *MRtrix3* changes, I then have to update this script to be compatible with those *other* *MRtrix3* changes as well. Once I've done that test, I'll commit and tag, and it then takes a half day or so to appear on Docker Hub.

**Pull request merged**
