### PR TITLE
Version 0.3.0

### PR DESCRIPTION
**Pull request by Lestropie**
Various changes that have been accumulating over time:

- Updated versions of various software dependencies.

- FreeSurfer's `recon-all` script will be run multi-threaded if appropriate.

- Additional parcellation schemes.

- Non-linear registration to MNI template for volumetric parcellations.

- Better control of the amount of output files provided by the script via option `--output_verbosity`. Also additional non-critical files are generated when this verbosity is high.

- Use combination of N4 and ROBEX for T1 brain extraction.

- Added standardised BIDS Apps option `--skip-bids-validator`.

- References now appear in command help page.

- Support for new capabilities of FSL `eddy` command.

- Option `--debug` will place the script temporary directory in the output folder, so that if the script fails, its contents can be investigated.

### CODE REVIEW

**Comment by Lestropie** [comment]
@chrisfilo: Version `0.3.0` is now up on [Docker Hub](https://hub.docker.com/r/bids/mrtrix3_connectome/tags/); feel free to host on OpenNeuro. Changes from `0.2.2` are described in this PR.

**Comment by chrisfilo** [comment]
Thanks for the info - I deployed the new version on OpenNeuro.

**Comment by Lestropie** [comment]
@chrisfilo: Is the repo information listed on [Docker Hub](https://hub.docker.com/r/bids/mrtrix3_connectome/) specified via copy-and-paste, rather than being generated automatically based on the repository's `README.md` file? It's currently not reflecting the [updated contents](https://github.com/BIDS-Apps/MRtrix3_connectome/pull/25/files#diff-04c6e90faac2675aa89e2176d2eec7d8) of that file, and I don't appear to have any kind of admin access to the repository on Docker Hub.

**Comment by chrisfilo** [comment]
What's your docker hub user name? I'll grant you access.

Best,
Chris

**Comment by Lestropie** [comment]
"[lestropie](https://hub.docker.com/u/lestropie/)" (no caps) :+1:

**Comment by chrisfilo** [comment]
done
Best,
Chris

**Pull request merged**
