### PR TITLE
Tag 0.2.2

### PR DESCRIPTION
**Pull request by Lestropie**
Fix to reflect renaming of MRtrix3 `mrinfo` option `-json_export` being renamed to `-json_keyval` - as reported [here](https://github.com/BIDS-Apps/MRtrix3_connectome/pull/18#issuecomment-330144488).

Had to make various fixes to *MRtrix3* to get the script running to completion with a FreeSurfer parcellation. Most of these are changes to the Python scripting library that had not yet been adequately tested in isolation. These can be found in *MRtrix3* pull request [#1049](https://github.com/MRtrix3/mrtrix3/pull/1049).

Also changed FSL to use compressed NIfTI format. Although the un-compressed format would be preferable in this context (since if NIfTI files are only generated for compatibility of intermediate files with other software packages, compressing / uncompressing is a waste), the particular version of FSL distributed for Ubuntu 14.04 ignores the `FSLOUTPUTTYPE` environment variable; so this change is actually to make sure that *MRtrix3* can find the files generated by FSL.

Additional items now listed in #3 and #19.

### CODE REVIEW

**Comment by Lestropie** [comment]
@chrisfilo @ddshin: Version 0.2.2 is now up on Docker Hub. I've run this through complete data for both types of parcellation, so fingers crossed it'll work out of the box for you. Still plenty more things for me to work on over time though 😈

**Comment by chrisfilo** [comment]
Deployed!

**Comment by ddshin** [comment]
@Lestropie - Thanks, I was able to run the process all the way through without any issues. Exciting! Can you please confirm that the output files I got match what the app is designed to generate (see below)?

screen shot 2017-10-01 at 3 36 56 am

**Comment by Lestropie** [comment]
Yep, that's what I'd expect currently. At some later stage I'll add a command-line option that will provide flexibility in terms of the amount of subject data written to the output directory vs. discarded.

**Comment by ddshin** [comment]
Great. Can you help briefly with interpretations of the results and what additional analysis/visualization can be done?

sub-01_dwi.nii.gz has the same size (128x128x52x61) as the original data. Is this raw data after distortion correction?

sub-01_tdi.nii.gz has the size (128x128x52). What does the voxel intensity represent (a number roughly between 0 and 1)?

The response.txt file contains:
5246.709163948946 0 0 0 0 0
2558.251731008988 -1009.214384224482 220.332364698163 -35.52175138361492 4.701552188934084 1.736752571171827

Finally, what do the numbers in connectome/*.csv and connectome/*mu.txt represent?

**Comment by Lestropie** [comment]
Currently, you get:

- The diffusion data after all pre-processing.

- The TDI calculated at native resolution is really only there for verification that `tckgen` and `tcksift2` are doing as they should.

- The WM response function used for spherical deconvolution, as this must be used in the group-level connection density normalisation step.

- The SIFT proportionality coefficient (`mu.txt`), as this must also be used in group-level processing.

- The un-normalised connectivity matrix, for which many connectome analyses are applicable; though for some types of comparisons the normalised version resulting from the group-level analysis are preferable.

Version `0.3.0`, which I started working on over the weekend, will by default include many more intermediate output data that can be used for further analysis & visualisation.

**Comment by ddshin** [comment]
Thanks, Robert. Looking forward to 0.3.0.

**Pull request merged**
