### PR TITLE
dev: Updates for MRtrix 3.0.0

### PR DESCRIPTION
**Pull request by Lestropie**
These are changes I have made separately to the current contents of #62 in order to support my own processing developments. 

Still to do:

- ROBEX downloads from NITRC stopped working at some point. If automatic download of this package is being precluded (i.e. requires a user click) I will need to select and integrate some other T1w brain extraction pipeline;

- All sorts of TODO comments strewn throughout that I will need to either address or move into issues on GitHub.

Changes over and above #62:

- Installation of `eddy_qc`; this will be run by `dwifslpreproc` and the result written to the BIDS Derivatives directory;

- Ported to *MRtrix3* 3.0.0 Python API;

- Participant-level processing now occurs in two stages:

  - `participant1` performs strictly "pre-processing", and its output is pre-processed DWI data (similar to the now-removed `-preprocessed` option);

  - `participant2` deals with everything subsequent to this point;

  This makes "participant1" useful for non-connectome-construction applications.

- `mtnormalise` utilised;

- Support for complex input DWI data, where complex MP-PCA denoising will be performed;

- If DWI data acquired using monopolar diffusion sensitisation, use only the *b*=0 volumes at the start of each acquisition; intermediate *b*=0 volumes may suffer distortions from residual eddy currents from previous volumes, whereas `topup` assumes zero eddy current distortions (performs combination of rigid-body and non-linear susceptibility estimation, but no affine);

- Iterative refinement of DWI brain mask based on bias field correction;

- Pre-processed DWI naming better conforms to BIDS Derivatives.

### CODE REVIEW

**Comment by Lestropie** [comment]
Closes #72.

**Comment by BrainModes** [comment]
Error when building the Docker image:

error: numpy 1.13.3 is installed but numpy>=1.14.5 is required by {'scipy'}
The command '/bin/sh -c git clone https://git.fmrib.ox.ac.uk/matteob/eddy_qc_release.git /opt/eddyqc &&     cd /opt/eddyqc && git checkout v1.0.2 && python3 ./setup.py install && cd /' returned a non-zero code: 1

**Comment by Lestropie** [comment]
> error: numpy 1.13.3 is installed but numpy>=1.14.5 is required by {'scipy'}

Ugh... I've previously had trouble with that one going *the other way*: allowing the `eddyqc` setup to install `numpy` would result in a version that was *too new* for one of its own other dependencies. But there's a chance that whatever that was has resolved itself over time... Realistically it would be preferable for fixed versions of all dependencies to be utilised, I might have to go down that route.

Thanks for the report; I'll try to reproduce overnight.

**Comment by BrainModes** [comment]
RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir --upgrade --force-reinstall numpy

seems to have fixed it.

**Comment by Lestropie** [comment]
A straight Docker build on the current contents of this branch worked for me :sweat_smile: 

It was a forced install on `numpy` via `pip3` that caused me issues in the past (5d9f809d) and resulted in me instead installing `numpy` via `apt`. So there's a chance that utilising that code could cause the same issue to arise. One possible discrepancy though is that that original observation may have been made in the new native Singularity build rather than Docker.

I think I'll just go through both container recipes and force fixed software versions on dependencies, utilising `pip` where appropriate.

**Comment by BrainModes** [comment]
😅

Now I get 

error: numpy 1.18.5 is installed but numpy<1.17dev,>=1.8 is required by {'nibabel'}
The command '/bin/sh -c git clone https://git.fmrib.ox.ac.uk/matteob/eddy_qc_release.git /opt/eddyqc &&     cd /opt/eddyqc && git checkout v1.0.2 && python3 ./setup.py install && cd /' returned a non-zero code: 1

Seems like nibabel is really specific about its desired numpy version.

I will now force fix the version of numpy explicitely to <1.17dev,>=1.8 ....

**Comment by BrainModes** [comment]
Step 29/66 : RUN wget -q "http://ddl.escience.cn/f/IiyU?func=download&rid=8135438" -O /opt/freesurfer/average/rh.BN_Atlas.gcs
 ---> Running in 168c627ca165
The command '/bin/sh -c wget -q "http://ddl.escience.cn/f/IiyU?func=download&rid=8135438" -O /opt/freesurfer/average/rh.BN_Atlas.gcs' returned a non-zero code: 8

and similar for the following wget commands.

Temporarily solved by appending

| wc -l > /number

to wget commands in order to pipe the exit code of the wget away and only evaluate the exit code of the "wc" to determine success. Danger is that there is no check whether the download succeeded.

**Comment by Lestropie** [comment]
That `wget` call fails because the download itself is unavailable; see webpage [here](https://atlas.brainnetome.org/download.html). I've had this once previously with this specific website. While I can pre-download a version of such files and host them somewhere myself for the container recipes to reference, I also don't want to redirect downloads away from the actual creators of such data. So what I need to do is set the recipes up to attempt to download from the original source, and only download from a source I set up myself if that download fails. This isn't too difficult, I've just got other things under time pressure right now.

**Comment by BrainModes** [comment]
Solved by replacing

        in_raw_t1w_paths = \
                glob.glob(os.path.join(bids_dir,
                                       'anat',
                                       session_label + '*_T1w.nii*'))

with
        in_raw_t1w_paths = glob.glob(os.path.join(os.path.join(bids_dir,
                                                               *session),
                                                  'anat',
                                                  '*_T1w.nii*'))

**Comment by Lestropie** [comment]
Comments in here are very much appreciated; it's a big changeset so there aren't smaller dedicated issues where such discussions would be better and more targeted.

Good catch on the raw T1w access. There are so many possibilities in terms of available data that I'm trying to code compatibility for, but I've not yet constructed test datasets to make sure they all function as expected...

**Pull request merged**
